<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Siswa;
use App\Models\Kelas;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kelasIds = Kelas::pluck('id')->toArray();

        if (empty($kelasIds)) {
            $this->command->warn('Tidak ada data kelas. Silakan buat kelas terlebih dahulu.');
            return;
        }

        $siswaData = [
            [
                'nis' => '2024001',
                'nisn' => '0012345678',
                'nik' => '3273010101050001',
                'nama_lengkap' => 'Ahmad Rizki Maulana',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2005-01-01',
                'alamat' => 'Jl. Sudirman No. 123, Bandung',
                'email' => 'ahmad.rizki@student.jibas.sch.id',
                'no_hp' => '081234567801',
                'nama_ayah' => 'Budi Santoso',
                'nama_ibu' => 'Siti Aminah',
                'no_hp_ortu' => '081234567901',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2024-07-01',
            ],
            [
                'nis' => '2024002',
                'nisn' => '0012345679',
                'nik' => '3273010202050002',
                'nama_lengkap' => 'Siti Nurhaliza',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2005-02-15',
                'alamat' => 'Jl. Merdeka No. 45, Jakarta Selatan',
                'email' => 'siti.nurhaliza@student.jibas.sch.id',
                'no_hp' => '081234567802',
                'nama_ayah' => 'Ahmad Dahlan',
                'nama_ibu' => 'Fatimah Zahra',
                'no_hp_ortu' => '081234567902',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2024-07-01',
            ],
            [
                'nis' => '2024003',
                'nisn' => '0012345680',
                'nik' => '3273010303050003',
                'nama_lengkap' => 'Budi Setiawan',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2005-03-20',
                'alamat' => 'Jl. Pahlawan No. 78, Surabaya',
                'email' => 'budi.setiawan@student.jibas.sch.id',
                'no_hp' => '081234567803',
                'nama_ayah' => 'Slamet Riyadi',
                'nama_ibu' => 'Dewi Sartika',
                'no_hp_ortu' => '081234567903',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2024-07-01',
            ],
            [
                'nis' => '2024004',
                'nisn' => '0012345681',
                'nik' => '3273010404050004',
                'nama_lengkap' => 'Dewi Lestari',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2005-04-10',
                'alamat' => 'Jl. Malioboro No. 56, Yogyakarta',
                'email' => 'dewi.lestari@student.jibas.sch.id',
                'no_hp' => '081234567804',
                'nama_ayah' => 'Bambang Sutrisno',
                'nama_ibu' => 'Sri Mulyani',
                'no_hp_ortu' => '081234567904',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2024-07-01',
            ],
            [
                'nis' => '2024005',
                'nisn' => '0012345682',
                'nik' => '3273010505050005',
                'nama_lengkap' => 'Eko Prasetyo',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2005-05-25',
                'alamat' => 'Jl. Pemuda No. 89, Semarang',
                'email' => 'eko.prasetyo@student.jibas.sch.id',
                'no_hp' => '081234567805',
                'nama_ayah' => 'Gunawan Wibowo',
                'nama_ibu' => 'Rina Susanti',
                'no_hp_ortu' => '081234567905',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2024-07-01',
            ],
            [
                'nis' => '2024006',
                'nisn' => '0012345683',
                'nik' => '3273010606050006',
                'nama_lengkap' => 'Fitri Handayani',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2005-06-12',
                'alamat' => 'Jl. Gatot Subroto No. 34, Medan',
                'email' => 'fitri.handayani@student.jibas.sch.id',
                'no_hp' => '081234567806',
                'nama_ayah' => 'Hendra Gunawan',
                'nama_ibu' => 'Yuni Astuti',
                'no_hp_ortu' => '081234567906',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2024-07-01',
            ],
            [
                'nis' => '2024007',
                'nisn' => '0012345684',
                'nik' => '3273010707050007',
                'nama_lengkap' => 'Gilang Ramadhan',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2005-07-08',
                'alamat' => 'Jl. A.P. Pettarani No. 67, Makassar',
                'email' => 'gilang.ramadhan@student.jibas.sch.id',
                'no_hp' => '081234567807',
                'nama_ayah' => 'Irfan Hakim',
                'nama_ibu' => 'Nurul Hidayah',
                'no_hp_ortu' => '081234567907',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2024-07-01',
            ],
            [
                'nis' => '2024008',
                'nisn' => '0012345685',
                'nik' => '3273010808050008',
                'nama_lengkap' => 'Hani Rahmawati',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '2005-08-18',
                'alamat' => 'Jl. Sudirman No. 12, Palembang',
                'email' => 'hani.rahmawati@student.jibas.sch.id',
                'no_hp' => '081234567808',
                'nama_ayah' => 'Joko Susilo',
                'nama_ibu' => 'Kartini Wijaya',
                'no_hp_ortu' => '081234567908',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2024-07-01',
            ],
            [
                'nis' => '2024009',
                'nisn' => '0012345686',
                'nik' => '3273010909050009',
                'nama_lengkap' => 'Indra Wijaya',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '2005-09-22',
                'alamat' => 'Jl. Sunset Road No. 90, Denpasar',
                'email' => 'indra.wijaya@student.jibas.sch.id',
                'no_hp' => '081234567809',
                'nama_ayah' => 'Ketut Suardana',
                'nama_ibu' => 'Luh Putu Ayu',
                'no_hp_ortu' => '081234567909',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2024-07-01',
            ],
            [
                'nis' => '2024010',
                'nisn' => '0012345687',
                'nik' => '3273011010050010',
                'nama_lengkap' => 'Kartika Sari',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Balikpapan',
                'tanggal_lahir' => '2005-10-05',
                'alamat' => 'Jl. MT. Haryono No. 23, Balikpapan',
                'email' => 'kartika.sari@student.jibas.sch.id',
                'no_hp' => '081234567810',
                'nama_ayah' => 'Made Wirawan',
                'nama_ibu' => 'Ni Nyoman Ayu',
                'no_hp_ortu' => '081234567910',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2024-07-01',
            ],
            [
                'nis' => '2023001',
                'nisn' => '0012345688',
                'nik' => '3273011111040001',
                'nama_lengkap' => 'Lukman Hakim',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2004-11-11',
                'alamat' => 'Jl. Asia Afrika No. 100, Bandung',
                'email' => 'lukman.hakim@student.jibas.sch.id',
                'no_hp' => '081234567811',
                'nama_ayah' => 'Nurdin Rahman',
                'nama_ibu' => 'Oki Setyana',
                'no_hp_ortu' => '081234567911',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2023-07-01',
            ],
            [
                'nis' => '2023002',
                'nisn' => '0012345689',
                'nik' => '3273011212040002',
                'nama_lengkap' => 'Maya Kusuma',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2004-12-16',
                'alamat' => 'Jl. Jenderal Sudirman No. 52, Jakarta',
                'email' => 'maya.kusuma@student.jibas.sch.id',
                'no_hp' => '081234567812',
                'nama_ayah' => 'Pandu Wijaya',
                'nama_ibu' => 'Qori Santika',
                'no_hp_ortu' => '081234567912',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2023-07-01',
            ],
            [
                'nis' => '2023003',
                'nisn' => '0012345690',
                'nik' => '3273010101040003',
                'nama_lengkap' => 'Nanda Pratama',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2004-01-20',
                'alamat' => 'Jl. Basuki Rahmat No. 88, Surabaya',
                'email' => 'nanda.pratama@student.jibas.sch.id',
                'no_hp' => '081234567813',
                'nama_ayah' => 'Rahmat Hidayat',
                'nama_ibu' => 'Sari Indah',
                'no_hp_ortu' => '081234567913',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2023-07-01',
            ],
            [
                'nis' => '2023004',
                'nisn' => '0012345691',
                'nik' => '3273010202040004',
                'nama_lengkap' => 'Olivia Putri',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2004-02-28',
                'alamat' => 'Jl. Kaliurang KM 5, Yogyakarta',
                'email' => 'olivia.putri@student.jibas.sch.id',
                'no_hp' => '081234567814',
                'nama_ayah' => 'Taufik Hidayat',
                'nama_ibu' => 'Umi Kalsum',
                'no_hp_ortu' => '081234567914',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2023-07-01',
            ],
            [
                'nis' => '2023005',
                'nisn' => '0012345692',
                'nik' => '3273010303040005',
                'nama_lengkap' => 'Putra Aditya',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2004-03-14',
                'alamat' => 'Jl. Pandanaran No. 45, Semarang',
                'email' => 'putra.aditya@student.jibas.sch.id',
                'no_hp' => '081234567815',
                'nama_ayah' => 'Vino Bastian',
                'nama_ibu' => 'Wulan Guritno',
                'no_hp_ortu' => '081234567915',
                'kelas_id' => $kelasIds[array_rand($kelasIds)],
                'status' => 'aktif',
                'tanggal_masuk' => '2023-07-01',
            ],
        ];

        foreach ($siswaData as $data) {
            Siswa::create($data);
        }

        $this->command->info('Berhasil menambahkan ' . count($siswaData) . ' data siswa.');
    }
}
